[package]
name = "toml_writer"
version = "1.1.1"
description = "A low-level interface for writing out TOML"
edition = "2021"
rust-version = "1.74"
license = "MIT OR Apache-2.0"
repository = "https://github.com/toml-rs/toml"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[lib]
name = "toml_writer"
path = "src/lib.rs"
